FROM centos:6
RUN yum install -y rpm-build\
	make\
	tar\
	gcc\
	gcc-c++\
	epel-release\
        http://tmn.sovzond.center/yum/RPMS/noarch/sovzond-center-repo-1.0.0-1.el6.noarch.rpm\
  && yum clean all
$YUM_COMMAND_TEMPLATE
WORKDIR /root 
COPY docker-entrypoint.sh /bin/entrypoint.sh
RUN chmod +x /bin/entrypoint.sh
ENTRYPOINT ["/bin/entrypoint.sh"]
